// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return basic info about the currently signed-in Irsyadul Haq user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = {
      userId: ctx.getUserId(),
      email: ctx.getUserEmail(),
      clientId: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-activities.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-activities.ts
var list_activities_default = defineTool2({
  name: "list_activities",
  title: "List santri activities",
  description: "List activities (kegiatan santri) for the pesantren. By default returns only published activities. Editors/admins can also see drafts by setting include_drafts=true.",
  inputSchema: {
    include_drafts: z.boolean().optional().describe("Include unpublished drafts. Only effective for editors/admins."),
    limit: z.number().int().min(1).max(100).optional().describe("Maximum rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_drafts, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("activities").select("id,title,description,date,time,location,participants,media_url,media_type,is_published,created_at,updated_at").order("date", { ascending: false }).limit(limit ?? 20);
    if (!include_drafts) query = query.eq("is_published", true);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { activities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-activity.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.23.8";
var create_activity_default = defineTool3({
  name: "create_activity",
  title: "Create santri activity",
  description: "Create a new kegiatan santri (activity) entry. Requires editor or admin role \u2014 enforced by database policies.",
  inputSchema: {
    title: z2.string().min(1).describe("Activity title."),
    description: z2.string().optional().describe("Optional description / body text."),
    date: z2.string().describe("Date in YYYY-MM-DD format."),
    time: z2.string().optional().describe("Optional time, e.g. '08:00'."),
    location: z2.string().optional(),
    participants: z2.string().optional().describe("Participants description, e.g. 'Kelas VII'."),
    media_url: z2.string().url().optional().describe("Optional image or video URL."),
    media_type: z2.enum(["image", "video"]).optional(),
    is_published: z2.boolean().optional().describe("Publish immediately (default false).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("activities").insert({ ...input, created_by: ctx.getUserId() }).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { activity: data }
    };
  }
});

// src/lib/mcp/tools/update-activity.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.23.8";
var update_activity_default = defineTool4({
  name: "update_activity",
  title: "Update santri activity",
  description: "Update fields of an existing kegiatan santri by id. Requires editor or admin role \u2014 enforced by database policies.",
  inputSchema: {
    id: z3.string().uuid().describe("Activity UUID."),
    title: z3.string().min(1).optional(),
    description: z3.string().optional(),
    date: z3.string().optional().describe("YYYY-MM-DD"),
    time: z3.string().optional(),
    location: z3.string().optional(),
    participants: z3.string().optional(),
    media_url: z3.string().url().optional(),
    media_type: z3.enum(["image", "video"]).optional(),
    is_published: z3.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("activities").update(patch).eq("id", id).select().maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "Activity not found or not permitted." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { activity: data }
    };
  }
});

// src/lib/mcp/tools/delete-activity.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.23.8";
var delete_activity_default = defineTool5({
  name: "delete_activity",
  title: "Delete santri activity",
  description: "Delete a kegiatan santri by id. Requires admin role \u2014 enforced by database policies.",
  inputSchema: {
    id: z4.string().uuid().describe("Activity UUID.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("activities").delete().eq("id", id);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Deleted activity ${id}` }],
      structuredContent: { id, deleted: true }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dounqhvrpynccsouarwe";
var mcp_default = defineMcp({
  name: "irsyadulhaq-mcp",
  title: "Irsyadul Haq Manado",
  version: "0.1.0",
  instructions: "Tools for the Pondok Pesantren Irsyadul Haq Manado website. Use `whoami` to verify sign-in, `list_activities` to read kegiatan santri, and `create_activity`/`update_activity`/`delete_activity` to manage them (editor/admin only, enforced by database policies).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_activities_default, create_activity_default, update_activity_default, delete_activity_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
